package:
  name: smesh
  version: "8.3.0.3"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja

  host:
    - occt ==7.4.0
    - boost-cpp
    - pthreads-win32  # [win]
    - netgen ==6.2.1808
    - tbb-devel
    - catch2

  run:
    - occt ==7.4.0
    - vtk
    - boost-cpp
    - pthreads-win32 # [win]
    - netgen ==6.2.1808

about:
  home: https://github.com/LaughlinResearch/SMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Mesh library from SALOME
  description: Standalone version of the meshing library from the Salome Platform.
