package:
  name: smesh
  version: "8.3.0.3"

source:
  path: ../..

build:
  number: 0
  features:
    - vc14 # [win]

requirements:
  build:
    - vc 14 # [win]
    - cmake
    - ninja
    - occt
    - vtk
    - boost-cpp
    - pthreads-win32 # [win]
    - netgen
    - tbb-devel

  run:
    - vc 14 # [win]
    - occt
    - vtk
    - boost-cpp
    - pthreads-win32 # [win]
    - netgen

about:
  home: https://github.com/LaughlinResearch/SMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Mesh library from SALOME
  description: Standalone version of the meshing library from the Salome Platform.
