package:
  name: smesh4pyocct
  version: "8.3.0.3"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - cmake
    - ninja

  host:
    - occt ==7.4.0
    - boost-cpp
    - pthreads-win32  # [win]
    - netgen4smesh ==6.2.1804
    - tbb-devel
    - vtk ==8.2.0
    - catch2

  run:
    - occt ==7.4.0
    - vtk ==8.2.0
    - boost-cpp
    - pthreads-win32 # [win]
    - netgen4smesh ==6.2.1804

about:
  home: https://github.com/LaughlinResearch/SMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Mesh library from SALOME
  description: Standalone version of the meshing library from the Salome Platform.
